name: Store App
defaults:
  run:
    shell: bash
    working-directory: ./store
    
on:
  push:
    branches: [ development ]
  pull_request:
    branches: [ development ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Installation
      run: |
       make install
 
    - name: Tests
      run: |
       make test
